In [1]:
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.cv.Z

--2020-04-17 15:01:30--  http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.cv.Z
Resolving archive.ics.uci.edu (archive.ics.uci.edu)...128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:80...connected.
HTTP request sent, awaiting response...200 OK
Length: 72777 (71K) [application/x-httpd-php]
Saving to: ‘optdigits-orig.cv.Z’

optdigits-orig.cv.Z 100%[===================>]  71.07K  15.5KB/s    in 4.6s    

2020-04-17 15:01:36 (15.5 KB/s) - ‘optdigits-orig.cv.Z’ saved [72777/72777]



In [2]:
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.names
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.tra.Z
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.wdep.Z
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.windep.Z


--2020-04-17 15:08:44--  http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.names
Resolving archive.ics.uci.edu (archive.ics.uci.edu)...128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:80...connected.
HTTP request sent, awaiting response...200 OK
Length: 2388 (2.3K) [application/x-httpd-php]
Saving to: ‘optdigits-orig.names’

optdigits-orig.name 100%[===================>]   2.33K  --.-KB/s    in 0s      

2020-04-17 15:08:46 (255 MB/s) - ‘optdigits-orig.names’ saved [2388/2388]

--2020-04-17 15:08:47--  http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits-orig.tra.Z
Resolving archive.ics.uci.edu (archive.ics.uci.edu)...128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:80...connected.
HTTP request sent, awaiting response...200 OK
Length: 145435 (142K) [application/x-httpd-php]
Saving to: ‘optdigits-orig.tra.Z’

optdigits-orig.tra. 100%[===================>] 1

In [6]:
!uncompress optdigits-orig.windep.Z

In [8]:
from time import time 
import matplotlib.pyplot as plt
import numpy as np 
from matplotlib import offsetbox
from sklearn import (manifold, datasets, decomposition, ensemble, discriminant_analysis, random_projection)

In [11]:
digits = datasets.load_digits(n_class=6)
X = digits.data
y = digits.target


In [10]:
print(digits.data)
print(digits.target)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  0. ...  9.  0.  0.]
 [ 0.  0.  0. ...  4.  0.  0.]
 [ 0.  0.  6. ...  6.  0.  0.]]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 0 4 1 3 1 0 0 2 2 2 0 1 2 3 3 3 3 4 4 1 0
 2 2 0 0 1 3 2 1 4 3 1 3 1 4 3 1 4 0 3 1 4 4 2 2 2 4 4 0 0 1 2 3 4 0 1 2 3
 4 0 1 2 3 4 0 0 4 1 3 1 0 0 2 2 2 0 1 2 3 3 3 3 4 4 1 0 2 2 0 0 1 3 2 1 3
 1 3 1 4 3 1 4 0 3 1 4 4 2 2 2 4 4 0 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 0 4 1
 3 1 0 0 2 2 2 0 1 2 3 3 3 3 4 4 1 0 2 2 0 0 1 3 2 1 4 3 1 3 1 4 3 1 4 0 3
 1 4 4 2 2 2 4 4 0 3 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 0 4 1 3 1 0 0 2 2 2 0
 1 2 3 3 3 3 4 4 1 0 2 2 0 0 1 3 2 1 4 3 1 3 1 4 3 1 4 0 3 1 4 4 2 2 2 4 4
 0 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 0 4 1 3 1 0 0 2 2 2 0 1 2 3 3 3 3 4 4 1
 0 2 2 0 0 1 3 2 1 4 3 1 3 1 4 3 1 4 0 3 1 4 4 2 2 2 4 4 0 0 1 2 3 4 0 1 2
 3 4 0 1 2 3 4 0 0 4 1 3 1 0 0 2 2 2 0 1 2 3 3 3 3 4 4 1 0 2 2 0 0 1 3 2 1
 4 3 1 3 1 4 3 1 4 0 3 1 4 4 2 2 2 4 4 0 0 1 2 3 4 0 1 2 3

In [ ]:
data, target = dataset.load_digits(n_class=6, )